# Header
menu:
  Home: /
  Professor: /professor
  Research: /research
  Member: /member
  Project: /project
  About: /about
rss: /

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: 
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

#custom
facebook: https://www.facebook.com/groups/sqlab.nctu/
github: https://github.com/SQLab

